(require 'javamonkey)

(global-set-key [(control ?=)]    'javamonkey-align)
(global-set-key [(control j)]     'join-line)
(global-set-key [(meta g)]        'goto-line)
(global-set-key [(control f6)]    'javamonkey-clear-imported-type)
(global-set-key [(control right)] 'javamonkey-fill-to-right)
(global-set-key [f10]             'p4-edit)
(global-set-key [f11]             'p4-revert)
(global-set-key [f12]             'p4-diff)
(global-set-key [f2]              'compile)
(global-set-key [f3]              'next-error)
(global-set-key [f4]              'tempo-template-java-get-set)
(global-set-key [f5]              'javamonkey-switch-to-test-or-src)
(global-set-key [f6]              'javamonkey-import-type)
(global-set-key [(shift f6)]      'javamonkey-refresh-imports)
(global-set-key [f7]              'javamonkey-fixme-comment)
(global-set-key [f8]              'javamonkey-review-comment)
(global-set-key [f9]              'javamonkey-super-jump-to-source)
(global-set-key [(shift f9)]      'javamonkey-jump-to-source-from-findstr)

(provide 'javamonkey-keybindings)